---
  :address:         smtp.gmail.com
  :port:            587
  :domain:          gmail.com
  :user_name:       joshholt.testaccount@gmail.com
  :password:        I$tanB00L
  :authentication:  plain
  :tls:             true